"""Central configuration for the QGAN project.

Single source of truth for paths, constants, and feature lists.
Every script must import from here instead of redefining its own copies.

Design rules:
  * Derived data files (everything under data/processed/*.csv and outputs/)
    are NOT committed to git; they are regenerated by the pipeline.
  * Small metadata (label_mapping.json, selected_features_25.json,
    feature_importances.csv) IS committed for reference.
  * The manual 16-feature choice lives HERE (versioned in code), not in a
    loose script. Changing it is a reviewable one-line diff.
"""

import json
import os
import random

import numpy as np

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

DATA_RAW_DIR = os.path.join(PROJECT_ROOT, "data", "processed", "MalayaNetwork_GT", "csv_output")
DATA_PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data", "processed")
OUTPUTS_DIR = os.path.join(PROJECT_ROOT, "outputs")

# Pipeline artifacts: chained names, one file = one content, no in-place
# overwrites. Rerunning any stage is idempotent.
MERGED_FILE = os.path.join(DATA_PROCESSED_DIR, "merged_cleaned_dataset.csv")   # clean_data.py output (62-dim)
SPLIT62_TRAIN = os.path.join(DATA_PROCESSED_DIR, "split62_train.csv")          # split_dataset.py outputs (62-dim)
SPLIT62_TEST = os.path.join(DATA_PROCESSED_DIR, "split62_test.csv")
FEATURES25_TRAIN = os.path.join(DATA_PROCESSED_DIR, "features25_train.csv")    # feature_selection.py outputs (auto top-25)
FEATURES25_TEST = os.path.join(DATA_PROCESSED_DIR, "features25_test.csv")
FEATURES16_TRAIN = os.path.join(DATA_PROCESSED_DIR, "features16_train.csv")    # select_manual_features.py outputs (manual 16)
FEATURES16_TEST = os.path.join(DATA_PROCESSED_DIR, "features16_test.csv")

LABEL_MAPPING_FILE = os.path.join(DATA_PROCESSED_DIR, "label_mapping.json")
SELECTED25_JSON = os.path.join(DATA_PROCESSED_DIR, "selected_features_25.json")
FEATURE_IMPORTANCES_FILE = os.path.join(DATA_PROCESSED_DIR, "feature_importances.csv")
CLEANING_REPORT_FILE = os.path.join(DATA_PROCESSED_DIR, "cleaning_report.txt")
SPLIT_MANIFEST_FILE = os.path.join(DATA_PROCESSED_DIR, "split_manifest.json")

# Metadata columns: carried through cleaning/splitting for grouping and
# auditing, NEVER used as model features.
SESSION_COLUMN = "session_id"
METADATA_COLUMNS = [SESSION_COLUMN, "Label_Name"]

MODELS_DIR = os.path.join(OUTPUTS_DIR, "models", "qgan_0-9")
RESULTS_DIR = os.path.join(OUTPUTS_DIR, "results")
BALANCED_QGAN_FILE = os.path.join(DATA_PROCESSED_DIR, "Train_Balanced_QGAN.csv")
BALANCED_CTGAN_FILE = os.path.join(DATA_PROCESSED_DIR, "Train_Balanced_CTGAN.csv")


def qgan_model_dir(label: int) -> str:
    """Directory holding weights/scaler/report/synthetic csv for one class."""
    return os.path.join(MODELS_DIR, str(label))


def qgan_synthetic_file(label: int) -> str:
    return os.path.join(qgan_model_dir(label), "Synthetic_Traffic_16dim.csv")


# --- generator-agnostic layout (QGAN / CTGAN / classical control) ----------
def generator_model_dir(generator: str, label: int) -> str:
    """generator in {"qgan", "ctgan", "classical"}. qgan keeps its legacy path."""
    if generator == "qgan":
        return qgan_model_dir(label)
    return os.path.join(OUTPUTS_DIR, "models", generator, str(label))


def synthetic_file(generator: str, label: int) -> str:
    return os.path.join(generator_model_dir(generator, label), "synthetic.csv")


# --- training-set conditions for the downstream comparison -----------------
CONDITIONS_DIR = os.path.join(DATA_PROCESSED_DIR, "conditions")
TRAIN_CONDITIONS = ["baseline", "undersample", "oversample", "smote", "qgan", "ctgan", "classical"]


def condition_file(name: str) -> str:
    return os.path.join(CONDITIONS_DIR, f"Train_{name}.csv")


# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------
SEED = 42


def set_seed(seed: int = SEED) -> None:
    """Seed python / numpy / torch. Call at the top of every entry script."""
    random.seed(seed)
    np.random.seed(seed)
    try:
        import torch
        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    except ImportError:
        pass


# ---------------------------------------------------------------------------
# Dataset constants
# ---------------------------------------------------------------------------
NUM_CLASSES = 10
LABEL_COLUMN = "Label"
TRAIN_RATIO = 0.8
TEST_RATIO = 1.0 - TRAIN_RATIO

# Class balancing target: classes with >= TARGET_TOTAL_SAMPLES real training
# rows are treated as majority (undersampled to this number); the rest are
# topped up to this number with synthetic rows.
TARGET_TOTAL_SAMPLES = 2000


def get_majority_labels(train_csv: str = None, threshold: int = TARGET_TOTAL_SAMPLES) -> set:
    """Derive majority classes from actual training counts.

    Replaces the hardcoded {0, 3, 6}: if the label mapping or the data ever
    changes again, this stays correct automatically.
    """
    import pandas as pd
    path = train_csv or FEATURES16_TRAIN
    counts = pd.read_csv(path, usecols=[LABEL_COLUMN])[LABEL_COLUMN].value_counts()
    return set(counts[counts >= threshold].index.astype(int))


def load_label_mapping() -> dict:
    with open(LABEL_MAPPING_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Feature lists
# ---------------------------------------------------------------------------
# Stage 1 (automated): feature_selection.py picks top-25 by train-only CV RF
# importance and writes SELECTED25_JSON. Read it at runtime, never hardcode.
def load_selected_25() -> list:
    with open(SELECTED25_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


# Stage 2 (MANUAL): the 16 features actually fed to the QGAN, hand-picked
# from the automated top-25. ORDER MATTERS and is part of the model
# definition: the circuit maps column i -> qubit wire i, wires 0-13 are the
# numerical register, wires 14-15 the discrete flag register.
#
# NOTE (known, deliberate for now): pkt_len_var and pkt_len_std are
# deterministically redundant (std = sqrt(var)). Swapping one out is a
# one-line edit here; do it as a controlled experiment, not silently.
NUMERIC_FEATURES = [
    # ranks 1-14 by session-grouped permutation importance (GroupKFold by
    # session_id, RF, f1_macro, Spearman|rho|>0.90 pre-pruned), computed on
    # the deduped session-split training data. See reports/feature_selection_16.md.
    "bwd_seg_size_avg", "pkt_len_min", "fwd_pkt_len_min", "totlen_bwd_pkts",
    "fwd_pkt_len_max", "bwd_pkt_len_min", "pkt_len_mean", "fwd_pkt_len_std",
    "bwd_pkt_len_std", "flow_byts_s", "fwd_pkt_len_mean", "psh_flag_cnt",
    "down_up_ratio", "fwd_act_data_pkts",
]
DISCRETE_FEATURES = [
    # genuinely discrete flag counts (nunique 8 and 12) for the discrete
    # register wires 14-15; the previous psh features were counts up to ~3200.
    "syn_flag_cnt", "fin_flag_cnt",
]
MANUAL_FEATURES_16 = NUMERIC_FEATURES + DISCRETE_FEATURES

NUM_NUMERIC = len(NUMERIC_FEATURES)   # 14 -> wires 0..13
N_QUBITS = len(MANUAL_FEATURES_16)    # 16
assert N_QUBITS == NUM_NUMERIC + len(DISCRETE_FEATURES)


def assert_feature_frame(df, where: str = "") -> None:
    """Fail fast if a dataframe does not contain the 16 features in order.

    Call before any model consumes data: silently reordered or missing
    columns must crash, not train on the wrong wires.
    """
    cols = [c for c in df.columns if c != LABEL_COLUMN]
    missing = [c for c in MANUAL_FEATURES_16 if c not in cols]
    if missing:
        raise ValueError(f"[{where}] missing features: {missing}")
    if cols[:N_QUBITS] != MANUAL_FEATURES_16:
        raise ValueError(
            f"[{where}] feature column order does not match MANUAL_FEATURES_16; "
            "wire assignment would be wrong. Re-run select_manual_features.py."
        )


# ---------------------------------------------------------------------------
# QGAN hyperparameters (frozen as of impg@735bdfc; change only deliberately)
# ---------------------------------------------------------------------------
N_LAYERS = 3
BATCH_SIZE = 32
LAMBDA_GP = 10
N_CRITIC = 2          # generator updated every N_CRITIC-th batch
LR_GENERATOR = 0.015
LR_CRITIC = 0.001
ADAM_BETAS = (0.0, 0.9)
TOTAL_EPOCHS = 100
